[general]
live_config_reload = true
import = ["./github_dark.toml"]

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Block"

[font]
size = 14.0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 1.0

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[colors.normal]
black = '#222522'
red = '#ef6560'
green = '#3fb83f'
yellow = '#d4aa02'
blue = '#37aff6'
magenta = '#d38faf'
cyan = '#6fc5ef'
white = '#cfdfd5'
[colors.bright]
black = '#505250'
red = '#ff778f'
green = '#00c089'
yellow = '#cfc04f'
blue = '#32cfef'
magenta = '#af9fff'
cyan = '#5dc0aa'
white = '#808f80'
[colors.cursor]
cursor = '#35f038'
text = '#111111'
[colors.primary]
background = '#111111'
foreground = '#cfdfd5'
[colors.selection]
background = '#3a3027'
text = '#cfdfd5'